# Generated by Django 4.2.7 on 2023-11-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
        ("expenses", "0003_remove_vehicle_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle"
            ),
        ),
        migrations.AlterField(
            model_name="servicerecord",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle"
            ),
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
