# Generated by Django 4.2.7 on 2023-11-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_expense_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
