# Generated by Django 4.2.7 on 2023-11-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_alter_expense_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="vehicle",
        ),
    ]
