# Generated by Django 4.2.7 on 2023-11-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="license_number",
        ),
    ]
