# Generated by Django 4.2.7 on 2023-11-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="email",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="license_number",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="name",
        ),
        migrations.AddField(
            model_name="driver",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
