# Generated by Django 4.2.7 on 2023-11-26 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drivers", "0002_driver_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
        migrations.RemoveField(
            model_name="driver",
            name="email",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="name",
        ),
        migrations.AddField(
            model_name="driver",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="license_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="drivers_licenses/"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
