# Generated by Django 4.2.7 on 2023-11-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="servicerecord",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driver",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="ServiceRecord",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
