# Generated by Django 4.2.7 on 2023-11-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
